In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,WikiId,Class
count,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000
mean,654.590630,0.260369,2.297235,29.476705,0.500768,0.384793,33.074558,659.110599,2.293395
std,377.897699,0.439004,0.836325,12.900992,1.043813,0.866233,51.536689,380.385092,0.839971
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,327.250000,0.000000,2.000000,22.000000,0.000000,0.000000,7.895800,328.250000,2.000000
50%,654.500000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,662.500000,3.000000
75%,980.750000,1.000000,3.000000,35.000000,1.000000,0.000000,31.206250,987.750000,3.000000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200,1314.000000,3.000000

In [34]:
df = df[['Survived', 'Age', 'Fare', 'Pclass', 'SibSp', 'Parch']]

In [36]:
p1 = df.iloc[0]
p2 = df.iloc[50]

df.iloc[[0, 50]]

    Survived   Age     Fare  Pclass  SibSp  Parch
0        0.0  22.0   7.2500       3      1      0
50       0.0   7.0  39.6875       3      4      1

In [49]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = StandardScaler()
scaled_df = scaler.fit_transform(df[['Age', 'Fare', 'Pclass']])
scaled_df = pd.DataFrame(scaled_df, columns=['Age', 'Fare', 'Pclass'])

scaled_df.head()

        Age      Fare    Pclass
0 -0.579768 -0.501283  0.840625
1  0.660924  0.741674 -1.551710
2 -0.269595 -0.488181  0.840625
3  0.428294  0.388716 -1.551710
4  0.428294 -0.485754  0.840625

In [50]:
from scipy.spatial.distance import euclidean, cityblock, cosine

p1_scaled = scaled_df.iloc[0].values
p2_scaled = scaled_df.iloc[50].values

print('Euclidean distance:', euclidean(p1_scaled, p2_scaled))
print('Manhattan distance:', cityblock(p1_scaled, p2_scaled))
print('Cosine distance:', cosine(p1_scaled, p2_scaled))

Euclidean distance: 1.3226373942374066
Manhattan distance: 1.7927958351488718
Cosine distance: 0.25080576905245233