In [30]:
import pandas as pd
from scipy.spatial.distance import euclidean, cityblock, cosine
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [13]:
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')
df[['Name', 'Age']].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [47]:
df = df[['Survived', 'Age', 'Fare', 'Pclass']]
df.groupby('Survived').mean()

                Age       Fare    Pclass
Survived
0.0       29.938733  27.713339  2.418484
1.0       28.164218  48.304217  1.952802

In [25]:
p1 = df.iloc[0].values
p2 = df.iloc[50].values

df.iloc[[0, 50]]

    Survived   Age     Fare  Pclass
0        0.0  22.0   7.2500       3
50       0.0   7.0  39.6875       3

In [29]:
print('Euclidean distance:', euclidean(p1, p2))
print('Manhattan distance:', cityblock(p1, p2))
print('Cosine distance:', cosine(p1, p2))

Euclidean distance: 35.73781479399657
Manhattan distance: 47.4375
Cosine distance: 0.5224791407284491

In [48]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[['Age', 'Fare', 'Pclass']])
df_scaled = pd.DataFrame(df_scaled, columns=['Age', 'Fare', 'Pclass'])

In [49]:
df_scaled.head()

        Age      Fare    Pclass
0 -0.579768 -0.501283  0.840625
1  0.660924  0.741674 -1.551710
2 -0.269595 -0.488181  0.840625
3  0.428294  0.388716 -1.551710
4  0.428294 -0.485754  0.840625

In [52]:
df[df['Pclass'] == 3].mean()

Survived     0.167139
Age         25.732295
Fare        13.316878
Pclass       3.000000
dtype: float64