In [13]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [15]:
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')
df[["Name", "Age", "Fare"]].head()

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [ ]:
scaler = StandardScaler()
df[["Age", "Fare"]] = scaler.fit_transform(df[["Age", "Fare"]])
df[["Name", "Age", "Fare"]].head()

                                                Name       Age      Fare
0                            Braund, Mr. Owen Harris  0.273456  0.014151
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  0.473882  0.139136
2                             Heikkinen, Miss. Laina  0.323563  0.015469
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.436302  0.103644
4                           Allen, Mr. William Henry  0.436302  0.015713