In [ ]:
import pandas as pd
from scipy.spatial.distance import euclidean, cityblock, cosine



from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')

df = df[['Survived', 'Age', 'Fare', 'Pclass', 'SibSp', 'Parch']]
df.groupby('Survived').mean()

                Age       Fare    Pclass     SibSp     Parch
Survived
0.0       29.938733  27.713339  2.418484  0.509865  0.355140
1.0       28.164218  48.304217  1.952802  0.474926  0.469027

In [3]:
# Distance between two passengers
p1 = df.iloc[0][['Age', 'Fare', 'SibSp']].values
p2 = df.iloc[50][['Age', 'Fare', 'SibSp']].values
df.iloc[[0,50]][['Age', 'Fare', 'SibSp']]

     Age     Fare  SibSp
0   22.0   7.2500      1
50   7.0  39.6875      4

In [4]:
print('Euclidean Distance:', euclidean(p1, p2))
print('Manhattan Distance:', cityblock(p1, p2))
print('Cosine Distance:', cosine(p1, p2))

Euclidean Distance: 35.86351079091393
Manhattan Distance: 50.4375
Cosine Distance: 0.5252917366603462

In [ ]:
# Scaling and Normalization
scaler = MinMaxScaler()
df_scaled = df.copy()
df_scaled[['Age', 'Fare', 'SibSp']] = scaler.fit_transform(df[['Age', 'Fare', 'SibSp']])

df_scaled.describe()

,Survived,Age,Fare,Pclass,SibSp,Parch
count,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000
mean,0.260369,0.367114,0.064557,2.297235,0.062596,0.384793
std,0.439004,0.161606,0.100593,0.836325,0.130477,0.866233
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,0.273456,0.015412,2.000000,0.000000,0.000000
50%,0.000000,0.348616,0.028213,3.000000,0.000000,0.000000
75%,1.000000,0.436302,0.060911,3.000000,0.125000,0.000000
max,1.000000,1.000000,1.000000,3.000000,1.000000,9.000000

In [ ]:
p1_scaled = df_scaled.iloc[0].values
p2_scaled = df_scaled.iloc[50].values
df_scaled.iloc[[0,50]]
print('Euclidean Distance (Scaled):', euclidean(p1_scaled, p2_scaled))
print('Manhattan Distance (Scaled):', cityblock(p1_scaled, p2_scaled))
print('Cosine Distance (Scaled):', cosine(p1_scaled, p2_scaled))

Euclidean Distance (Scaled): 1.0862503288108394
Manhattan Distance (Scaled): 1.6262130693860408
Cosine Distance (Scaled): 0.05923782325299154

In [ ]:
x = [1, 2, 3, 4, 5]

dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

arr = np.array(x)