In [1]:
import pandas as pd
from scipy.spatial.distance import euclidean, cityblock, cosine
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')

df = df[['Survived', 'Age', 'Fare', 'Pclass', 'SibSp', 'Parch']]
df.groupby('Survived').mean()

                Age       Fare    Pclass     SibSp     Parch
Survived
0.0       29.938733  27.713339  2.418484  0.509865  0.355140
1.0       28.164218  48.304217  1.952802  0.474926  0.469027

In [3]:
# Distance between two passengers
p1 = df.iloc[0][['Age', 'Fare', 'SibSp']].values
p2 = df.iloc[50][['Age', 'Fare', 'SibSp']].values
df.iloc[[0,50]][['Age', 'Fare', 'SibSp']]

     Age     Fare  SibSp
0   22.0   7.2500      1
50   7.0  39.6875      4

In [4]:
print('Euclidean Distance:', euclidean(p1, p2))
print('Manhattan Distance:', cityblock(p1, p2))
print('Cosine Distance:', cosine(p1, p2))

Euclidean Distance: 35.86351079091393
Manhattan Distance: 50.4375
Cosine Distance: 0.5252917366603462

In [9]:
# Scaling and Normalization
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[['Age', 'Fare', 'SibSp']] = scaler.fit_transform(df[['Age', 'Fare', 'SibSp']])

p1_scaled = df_scaled.iloc[0].values
p2_scaled = df_scaled.iloc[50].values
df_scaled.iloc[[0,50]]

    Survived       Age      Fare  Pclass     SibSp  Parch
0        0.0 -0.579768 -0.501283       3  0.478461      0
50       0.0 -1.742916  0.128365       3  3.353643      1

In [6]:
print('Euclidean Distance (Scaled):', euclidean(p1_scaled, p2_scaled))
print('Manhattan Distance (Scaled):', cityblock(p1_scaled, p2_scaled))
print('Cosine Distance (Scaled):', cosine(p1_scaled, p2_scaled))

Euclidean Distance (Scaled): 3.164812920610336
Manhattan Distance (Scaled): 4.667977767797137
Cosine Distance (Scaled): 0.25347787695534485