In [2]:
import pandas as pd
df = pd.read_csv('../datasets/titanic/titanic_cleaned.csv')

In [3]:
# mean
mean_age = df['Age'].mean()
print("Mean age: ", mean_age)

mean_fare = df['Fare'].mean()
print("Mean fare: ", mean_fare)

Mean age:  29.476705069124424
Mean fare:  33.07455791090629

In [4]:
# variance
variance_age = df['Age'].var()
print("variance age: ", variance_age)

variance_fare = df['Fare'].var()
print("variance fare: ", variance_fare)

variance age:  166.43560612201887
variance fare:  2656.0302838251146

In [5]:
# Co-variance
cov_matrix = df[['Age', 'Fare', 'Pclass']].cov()
cov_matrix

               Age         Fare     Pclass
Age     166.435606   118.658227  -4.076022
Fare    118.658227  2656.030284 -23.976064
Pclass   -4.076022   -23.976064   0.699439

In [6]:
# Co-relation
corr_matrix = df[['Age', 'Fare', 'Pclass']].corr()
corr_matrix

             Age      Fare    Pclass
Age     1.000000  0.178467 -0.377780
Fare    0.178467  1.000000 -0.556271
Pclass -0.377780 -0.556271  1.000000

In [ ]:
# Grouped Statistics
df_new = df[['Survived', 'Age', 'Fare', 'Pclass']]
df_new.groupby('Pclass').mean()

        Survived        Age       Fare
Pclass
1       0.420063  37.813229  87.130787
2       0.314079  29.419675  21.179196
3       0.167139  25.732295  13.316878

In [ ]:
import numpy as np

age = [32,43,54,65,34,32,3]
print(age[2])

age_n = np.array(age)
mean = np.mean(age)

In [ ]:
import cv2

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()